KCL-10481 - Properly track all necessary mutations when resolving com…
KenticoInternal/draft-js pull request #15
Opened 2023-04-21 10:05 UTC by hejtmii

2023-04-26 06:12 UTC, vilemj-Viclick requested changes

2023-04-26 06:12 UTC, vilemj-Viclick commented on src/component/selection/getOffsetKeyFromNode.js
> + *
Is it though?

I mean... This is not really a Facebook file...

2023-04-26 06:12 UTC, vilemj-Viclick commented on src/component/handlers/composition/DraftEditorCompositionHandler.js
> +      mutatedEditorState = EditorState.set(mutatedEditorState, {
You may want to explain why `set` and not `push`. Or in general why this unorthodox method?

2023-04-26 08:11 UTC, hejtmii commented on src/component/handlers/composition/DraftEditorCompositionHandler.js
> +      mutatedEditorState = EditorState.set(mutatedEditorState, {
This comes from the original code, I just moved it higher. `set` sets the properties, while `push` updates content, and (optionally) adds item to undo stack. They have quite different contract also

2023-04-26 08:12 UTC, hejtmii commented on src/component/selection/getOffsetKeyFromNode.js
> + *
Technically no, but I would like to create PR from this and every file has this regardless of the author :-)

2023-05-04 06:26 UTC, petersolar approved these changes

2023-05-05 11:51 UTC, hejtmii commented
Abandoning in favor of https://github.com/kontent-ai/draft-js/pull/17 which should be more reliable

2023-05-05 11:51 UTC, closed without merging