KCL-11106 - Update selection before handling input in case the select…
KenticoInternal/draft-js pull request #19
Opened 2023-09-01 14:00 UTC by hejtmii

See details in task

2023-09-08 06:40 UTC, vilemj-Viclick approved these changes
It's basically fine.
Just some nitpicks.

2023-09-08 06:40 UTC, vilemj-Viclick commented on src/component/handlers/edit/DraftEditorEditHandler.js
> +// event, causing problems with cursor positioning. Therefore, the selection
```
// event, causing problems with cursor positioning. Therefore, the selection
                                  ↑ Did you mean "caret"?
```

2023-09-08 06:40 UTC, vilemj-Viclick commented on src/component/handlers/edit/DraftEditorEditHandler.js
> +// state is always synced with the actual cursor positions.
```
// state is always synced with the actual cursor positions.
                                      ↑ current?
```

2023-09-08 06:40 UTC, vilemj-Viclick commented on src/component/handlers/edit/DraftEditorEditHandler.js
> +  const keyCode = e.which;
Aside from "e.which" being deprecated, this also works for detecting numpad keys when num-lock is off.
I could not think of any other key which would affect selection aside from "Meta". The key with the Windows logo on it. But that one basically takes focus away from the window entirely, so it's not that much of a problem, is it?

2023-09-08 06:40 UTC, vilemj-Viclick commented on src/component/handlers/edit/DraftEditorEditHandler.js
> +  isDown: boolean,
I don't like this boolean toggle, honestly.

Why not just have
```
function setTrackedKeyStatus(
  e: SyntheticKeyboardEvent<HTMLElement>,
) {
  // Same implementation except the "if"
};
```

and then reset the key on line 112 simply by
```
keysDown.delete(e.which);
```

2023-09-08 06:40 UTC, vilemj-Viclick commented on src/component/handlers/edit/DraftEditorEditHandler.js
> +  isDown: boolean,
Also... The variable called `keyCode` when you're specifically ignoring `e.keyCode` had me looking at the code in a wrong way for a while. I thought you were using `e.keycode` to tell apart keys. But they are practically equivalent. Both are deprecated. :D

2023-09-08 10:30 UTC, hejtmii commented on src/component/handlers/edit/DraftEditorEditHandler.js
> +  const keyCode = e.which;
I guess not. e.which is also used in keyboard shortcuts handling in other parts of the code, so if it stops working, we are in much larger trouble than just this :-)

2023-09-08 11:22 UTC, hejtmii commented on src/component/handlers/edit/DraftEditorEditHandler.js
> +  isDown: boolean,
True, I wanted to keep implementation details of how the keys are tracked in the same place. I got rid of the IF and made two methods instead

Regarding the `keyCode`, I literally copied the code from `editOnKeyDown.js` to keep things consistent with existing code that works in a similar way and with the same Keys constants

2023-09-08 11:22 UTC, hejtmii commented on src/component/handlers/edit/DraftEditorEditHandler.js
> +// state is always synced with the actual cursor positions.
updated

2023-09-08 11:25 UTC, hejtmii commented on src/component/handlers/edit/DraftEditorEditHandler.js
> +// event, causing problems with cursor positioning. Therefore, the selection
This is comment from original DraftJS code, just move higher, I didn't want to touch it on purpose. Keeping it

2023-09-11 04:04 UTC, vilemj-Viclick approved these changes
Now it's even more fine. 😄 
:shipit:

2023-09-27 06:23 UTC, vilemj-Viclick requested changes
![image](https://github.com/kontent-ai/draft-js/assets/13902120/c8931552-9395-4c9d-aab1-d1e0e8567d65)
Please remove the browser specification here as we handle these events in all of them and we know for a fact it also happens in other browsers.

2023-09-27 10:21 UTC, vilemj-Viclick approved these changes

2023-09-27 10:22 UTC, merged